# Generated by Django 5.2.5 on 2026-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('student_id', models.IntegerField()),
                ('when_purchased', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField()),
            ],
        ),
    ]
