# Generated by Django 5.2.5 on 2026-01-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_info',
            name='when_purchased',
        ),
        migrations.AddField(
            model_name='purchase_info',
            name='picup_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_info',
            name='delivery_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
