# Generated by Django 5.2.5 on 2026-01-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchase_info_when_purchased_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_info',
            old_name='names',
            new_name='book_name',
        ),
    ]
